# NumPy Assesment - Single Question

**Complete this one problem that combines ALL NumPy concepts**

---

## The Challenge: Stock Market Data Analysis

You work for a financial firm. You have 3 months of stock data for 4 companies:

```
Prices by week (4 weeks per month, 3 months = 12 weeks):

Company A: [105, 108, 110, 107, 112, 115, 118, 120, 119, 122, 125, 128]
Company B: [50,  52,  48,  51,  55,  53,  52,  58,  60,  58,  62,  65]
Company C: [200, 195, 198, 192, 190, 188, 185, 182, 180, 178, 175, 172]
Company D: [75,  78,  80,  82,  85,  83,  84,  86,  88,  87,  89,  91]
```

**TASK: Complete ALL of the following (you must do every single one):**

1. **Create a 4×12 matrix** where each row is a company, each column is a week

2. **Calculate each company's statistics:**
   - Mean price (average over 12 weeks)
   - Median price
   - Price volatility (standard deviation)

3. **Reshape the data** into 3 months of 4-week blocks (shape: 3×4×4) and calculate each company's monthly average

4. **Use boolean indexing** to:
   - Find weeks where Company A price > 115
   - Find weeks where Company C price < 190
   - Create a new matrix with "UP" for weeks where price increased from previous week, "DOWN" for decreases (dtype=object)

5. **Calculate correlation using dot product:**
   - Normalize Company A prices: (price - mean) / std
   - Normalize Company B prices: (price - mean) / std
   - Use np.dot() to find correlation between normalized A and B

6. **Identify the best performing company:**
   - Calculate total growth: final_price - initial_price
   - Calculate percentage growth: (growth / initial_price) × 100
   - Use np.argmax() to find which company had highest growth %
   - Print company name and growth percentage

7. **BONUS (+20 points): Find the optimal portfolio:**
   - Allocate investment (out of 100%) to minimize risk (std) while maximizing return (mean)
   - Use dot product to calculate portfolio mean and std
   - Suggest best allocation weights for each company

In [30]:
import numpy as np

array = np.array([[105, 108, 110, 107, 112, 115, 118, 120, 119, 122, 125, 128],
                  [50,  52,  48,  51,  55,  53,  52,  58,  60,  58,  62,  65],
                  [200, 195, 198, 192, 190, 188, 185, 182, 180, 178, 175, 172],
                  [75,  78,  80,  82,  85,  83,  84,  86,  88,  87,  89,  91]])
#array = np.sort(array)

companies = ["A", "B", "C", "D"]
company_stats = {}

for i, company_name in enumerate(companies):
    company_stats[company_name] = {
        "mean": np.mean(array[i]),
        "median": np.median(array[i]),
        "standardDeviation": np.std(array[i])
    }

# Print individual companies one by one
print(f"Company A: Mean = {company_stats['A']['mean']:.2f}")

Company A: Mean = 115.75


enumerate(companies) always returns pairs in this order: (index, value)

So it gives you:

(0, "A")
(1, "B")
(2, "C")
(3, "D")

In [ ]:
reshaped = array.reshape(4, 3, 4)
print(reshaped)
# RESULT [[comp_A_month1, comp_B_month1, comp_C_month1, comp_D_month1],
#  [comp_A_month2, comp_B_month2, comp_C_month2, comp_D_month2],
#  [comp_A_month3, comp_B_month3, comp_C_month3, comp_D_month3]]


[[[105 108 110 107]
  [112 115 118 120]
  [119 122 125 128]]

 [[ 50  52  48  51]
  [ 55  53  52  58]
  [ 60  58  62  65]]

 [[200 195 198 192]
  [190 188 185 182]
  [180 178 175 172]]

 [[ 75  78  80  82]
  [ 85  83  84  86]
  [ 88  87  89  91]]]


The 3rd question asks you to:

Reshape the data from (4, 12) into (3, 4, 4)
Calculate monthly averages for each company
Breaking it down:

Current shape: (4 companies, 12 weeks)

New shape: (3 months, 4 companies, 4 weeks per month)

Month 1: weeks 1-4
Month 2: weeks 5-8
Month 3: weeks 9-12