In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[0])

[1 2 3 4]


ROW SELECTION

In [17]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[::2]) #if its blank means select all

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[::-1]) # it would start from the bottom

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [18]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


###COLUMN SELECTION

In [20]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[0,0]) #1st index is for the row and the second is for the column

1


In [37]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[:, 0]) #select all rows, access column 0

[ 1  5  9 13]


In [55]:
array = np.array([
    [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
    [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
    [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
    [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
    [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
    [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
    [91, 92, 93, 94, 95, 96, 97, 98, 99,100]
]) #2d arrays
#array[start:end:step]

print(array[::-1, 0]) # reversed
#remember that the first is about the row and the second is about the column

[91 81 71 61 51 41 31 21 11  1]


In [ ]:
array = np.array([
    [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
    [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
    [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
    [51, 52, 53, 54, 55, 56, 57, 58, 59, 60],
    [61, 62, 63, 64, 65, 66, 67, 68, 69, 70],
    [71, 72, 73, 74, 75, 76, 77, 78, 79, 80],
    [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
    [91, 92, 93, 94, 95, 96, 97, 98, 99,100]
]) #2d arrays
#array[start:end:step]

print(array[::-1, 0::2])  # Select every other column 
#(step 2), from all rows in reverse order (bottom to top)

[[91 93 95 97 99]
 [81 83 85 87 89]
 [71 73 75 77 79]
 [61 63 65 67 69]
 [51 53 55 57 59]
 [41 43 45 47 49]
 [31 33 35 37 39]
 [21 23 25 27 29]
 [11 13 15 17 19]
 [ 1  3  5  7  9]]
