# RESHAPE
reshape() = Changes the shape of an array w/o alyterig its underlying data

.reshape(rows, columns)

In [13]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                  [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
print(array.shape)#2 rows, 12 columns

(2, 12)


### make if you are reshaping an array that it is able to be reshaped,
### for example
12 sets of array  can be reshaped as:

2 rows and 6 columns

1 row 12 column

4 rows 3 columns
### obviously if because 4 * 3 is 12 etc
if you try to reshape it to something like 2 rows and 5 columns, it would be a syntax error

In [14]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

array = array.reshape(2,6)
print(array)#2 rows 6 columns

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [15]:
array = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                  [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
array = array.reshape(4,6)
print(array) #4 rows, 6 columns

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
