In [ ]:
import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[0])

[1 2 3 4]


ROW SELECTION

In [17]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[0:4:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[::2]) #if its blank means select all

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [ ]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[::-1]) # it would start from the bottom

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [18]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


COLUMN SELECTION

In [20]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[0,0]) #1st index is for the row and the second is for the column

1


In [37]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[:, 0]) #select all rows, access column 0

[ 1  5  9 13]


In [41]:
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12],
                  [13, 14, 15, 16]]) #2d array

#array[start:end:step]

print(array[::-1, 0]) # reversed
#remember that the first is about the row and the second is about the column

[13  9  5  1]
